export const PROCTORING_CONFIG = {
    MODELS_PATH: '/models',
    MAX_VIOLATIONS_ALLOWED: 8,
    TOAST_COOLDOWN_MS: 15000,
    VIOLATION_COOLDOWN_MS: 15000,
    FULLSCREEN_TRANSITION_TIMEOUT_MS: 30000,
    FAILED_UPLOAD_RECOVERY_WINDOW_MS: 3600000,
    FAILED_UPLOAD_CLEANUP_MS: 86400000,
};
export const FACE_ANALYSIS_CONFIG = {
    DETECTOR_INPUT_SIZE: 320,
    DETECTOR_SCORE_THRESHOLD: 0.5,
    VIOLATION_THRESHOLD_FRAMES: 10,
    VIOLATION_RESET_FRAMES: 5,
    MIN_FACE_SIZE: 50,
    NO_FACE_THRESHOLD_FRAMES: 3,
    HEAD_YAW_TURNED_THRESHOLD: 40,
    HEAD_YAW_AWAY_THRESHOLD: 55,
    HEAD_PITCH_AWAY_THRESHOLD: 45,
    EAR_CLOSED_THRESHOLD: 0.18,
    LOOP_INTERVAL_MS: 1500,
    STARTUP_GRACE_PERIOD_MS: 3000,
};
export const RECORDER_CONFIG = {
    MIME_TYPE_VP9: 'video/webm; codecs=vp9,opus',
    MIME_TYPE_VP8: 'video/webm; codecs=vp8,opus',
    BITRATE_VIDEO: 2300000,
    BITRATE_AUDIO: 200000,
    TIMESLICE_MS: 120000,
    AUTO_SAVE_MIN_BLOB_SIZE_BYTES: 500 * 1024,
    UPLOAD_MAX_RETRIES: 3,
};
export const VIOLATION_TYPES = {
    DEVTOOLS_DEBUGGER: 'devtools_debugger_detected',
    TAB_SWITCHED: 'tab_switched_away',
    MULTIPLE_VIOLATIONS: 'multiple_violations',
    SCREEN_SHARE_STOPPED: 'screen_share_stopped',
    FULLSCREEN_EXITED: 'fullscreen_exited',
    WINDOW_LOST_FOCUS: 'window_lost_focus',
    SUSPICIOUS_HOTKEY: 'suspicious_hotkey',
    NO_FACE: 'no_face_detected',
    MULTIPLE_FACES: 'multiple_faces_detected',
    DEVTOOLS_OPENED: 'devtools_opened',
    CAMERA_ACCESS_DENIED: 'camera_access_denied',
    SCREEN_SHARE_DENIED: 'screen_share_denied',
    HEAD_TURNED: 'head_turned_significantly',
    LOOKING_AWAY: 'looking_away_from_screen',
    EYES_CLOSED: 'eyes_closed',
    TAB_RETURNED: 'tab_returned',
    WINDOW_GAINED_FOCUS: 'window_gained_focus',
    SCREEN_SHARE_NOT_ENTIRE: 'screen_share_not_entire_monitor',
    TEXT_COPIED: 'text_copied',
    TEXT_PASTED: 'text_pasted',
} as const;
